version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: afyatrack-web-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=hospitals
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - afyanet
    labels:
      - "com.afyatrack.service=web"
      - "com.afyatrack.version=1.0.0"

  db:
    image: postgres:13-alpine
    container_name: afyatrack-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hospitals
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - afyanet
    ports:
      - "5432:5432"
    labels:
      - "com.afyatrack.service=database"

volumes:
  postgres_data:

networks:
  afyanet:
    driver: bridge