apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: afyatrack-ke
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'localhost:587'
      smtp_from: 'alertmanager@afyatrack-ke.com'
      smtp_require_tls: false

    route:
      group_by: ['alertname', 'severity']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
      - match:
          severity: critical
        receiver: 'critical-alerts'
        repeat_interval: 10m
      - match:
          severity: warning
        receiver: 'warning-alerts'
      - match:
          severity: info
        receiver: 'info-alerts'

    receivers:
    - name: 'web.hook'
      webhook_configs:
      - url: 'http://localhost:5001/'

    - name: 'critical-alerts'
      webhook_configs:
      - url: 'http://webhook-service.afyatrack-ke.svc.cluster.local:8080/alerts'
        send_resolved: true
      email_configs:
      - to: 'admin@afyatrack-ke.com'
        subject: '[CRITICAL] {{ .GroupLabels.alertname }}'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .GroupLabels.severity }}
          Summary: {{ .CommonAnnotations.summary }}
          Description: {{ .CommonAnnotations.description }}

    - name: 'warning-alerts'
      webhook_configs:
      - url: 'http://webhook-service.afyatrack-ke.svc.cluster.local:8080/alerts'
        send_resolved: true

    - name: 'info-alerts'
      webhook_configs:
      - url: 'http://webhook-service.afyatrack-ke.svc.cluster.local:8080/alerts'
        send_resolved: true

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'namespace']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: afyatrack-ke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        ports:
        - containerPort: 9093
        args:
          - '--config.file=/etc/alertmanager/alertmanager.yml'
          - '--storage.path=/alertmanager'
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager/
        - name: alertmanager-storage
          mountPath: /alertmanager
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
      - name: alertmanager-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: afyatrack-ke
spec:
  selector:
    app: alertmanager
  ports:
  - port: 9093
    targetPort: 9093
  type: NodePort