apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: afyatrack-ke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin123
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboard-provisioning
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboard-provisioning
          configMap:
            name: grafana-dashboard-provisioning
        - name: grafana-dashboards
          projected:
            sources:
              - configMap:
                  name: grafana-default-dashboard
              - configMap:
                  name: grafana-dashboard-afyatrack

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: afyatrack-ke
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-service.afyatrack-ke.svc.cluster.local:8080
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 5s
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: afyatrack-ke
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort