---
- name: Configure AfyaTrack KE Server - Bonus Task
  hosts: afyatrack_servers
  become: yes
  vars:
    # Configuration variables
    devops_group: devops
    devops_user: devops
    config_file: config.txt
    
    # PostgreSQL configuration
    postgres_version: "15"
    
    # Nginx configuration
    nginx_site_name: "afyatrack-ke"

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required system packages
      apt:
        name:
          - curl
          - wget
          - gnupg
          - software-properties-common
          - ufw
        state: present

    - name: Create devops group
      group:
        name: "{{ devops_group }}"
        state: present

    - name: Create devops user
      user:
        name: "{{ devops_user }}"
        group: "{{ devops_group }}"
        shell: /bin/bash
        home: "/home/{{ devops_user }}"
        create_home: yes
        state: present

    - name: Add devops user to sudoers
      copy:
        content: "{{ devops_user }} ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/{{ devops_user }}"
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Set up SSH directory for devops user
      file:
        path: "/home/{{ devops_user }}/.ssh"
        state: directory
        owner: "{{ devops_user }}"
        group: "{{ devops_group }}"
        mode: '0700'

    - name: Add SSH public key for devops user from environment variable
      copy:
        content: "{{ lookup('env', 'SSH_PUBLIC_KEY') }}"
        dest: "/home/{{ devops_user }}/.ssh/authorized_keys"
        owner: "{{ devops_user }}"
        group: "{{ devops_group }}"
        mode: '0600'

    - name: Copy configuration file to /opt with devops group permissions
      copy:
        src: "{{ config_file }}"
        dest: "/opt/{{ config_file }}"
        owner: "{{ devops_user }}"
        group: "{{ devops_group }}"
        mode: '0664'

    - name: Install PostgreSQL
      block:
        - name: Add PostgreSQL APT repository
          apt_repository:
            repo: "deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
            state: present
            filename: postgresql

        - name: Import PostgreSQL signing key
          apt_key:
            url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
            state: present

        - name: Install PostgreSQL
          apt:
            name: "postgresql-{{ postgres_version }}"
            state: present
            update_cache: yes

    - name: Ensure PostgreSQL service is running and enabled
      systemd:
        name: "postgresql"
        state: started
        enabled: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx service is running and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Display configuration summary
      debug:
        msg: |
          ✅ AfyaTrack KE Server Configuration Complete!
          
          📊 Services Configured:
          - PostgreSQL {{ postgres_version }}: ✅ Installed and running
          - Nginx: ✅ Installed and running
          
          👥 User Configuration:
          - User '{{ devops_user }}' created with group '{{ devops_group }}'
          - SSH access configured for devops user
          - Sudo privileges granted
          
          📁 File Configuration:
          - Config file: /opt/{{ config_file }} (rw for {{ devops_group }} group)
          - Permissions: devops:devops with 664
          
          🔐 Security:
          - Non-root user SSH access: ✅ Configured
          - File permissions: ✅ Properly set
          - Services: ✅ Running and enabled

  handlers:
    - name: restart postgresql
      systemd:
        name: "postgresql"
        state: restarted

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted